##clickhouses数据源
spring:
  datasource:
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    jdbc-url: jdbc:clickhouse://172.20.72.205:8123/audit_wbapi
    username: default
    password: 123456
    hikari:
      auto-commit: true
      #空闲连接超时时长
      idle-timeout: 60000
      #连接超时时长
      connection-timeout: 3999999
      #最大生命周期，0不过期
      max-lifetime: 0
      #最小空闲连接数
      minimum-idle: 16
      #最大连接数量
      maximum-pool-size: 10


